/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as FaturaRouteImport } from './routes/fatura'
import { Route as FuturoRouteImport } from './routes/futuro'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const FaturaRoute = FaturaRouteImport.update({
  id: '/fatura',
  path: '/fatura',
  getParentRoute: () => rootRouteImport,
} as any)
const FuturoRoute = FuturoRouteImport.update({
  id: '/futuro',
  path: '/futuro',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/fatura': typeof FaturaRoute
  '/futuro': typeof FuturoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/fatura': typeof FaturaRoute
  '/futuro': typeof FuturoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/fatura': typeof FaturaRoute
  '/futuro': typeof FuturoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/fatura' | '/futuro'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/fatura' | '/futuro'
  id: '__root__' | '/' | '/auth' | '/fatura' | '/futuro'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  FaturaRoute: typeof FaturaRoute
  FuturoRoute: typeof FuturoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fatura': {
      id: '/fatura'
      path: '/fatura'
      fullPath: '/fatura'
      preLoaderRoute: typeof FaturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/futuro': {
      id: '/futuro'
      path: '/futuro'
      fullPath: '/futuro'
      preLoaderRoute: typeof FuturoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  FaturaRoute: FaturaRoute,
  FuturoRoute: FuturoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
